import { Router } from 'express';
import { getMe, login, logout, register } from '../controllers/authController.js';
import { requireAuth } from '../middleware/authMiddleware.js';
import { validateLogin, validateRegistration } from '../validators/authValidator.js';
const router = Router();
router.post('/register', validateRegistration, register);
router.post('/login', validateLogin, login);
router.get('/me', requireAuth, getMe);
router.post('/logout', requireAuth, logout);
export default router;
