import { Router } from 'express';
import { getPatientAnalytics, getPatientFeatureVectors } from '../controllers/analyticsController.js';
import { requireAuth } from '../middleware/authMiddleware.js';
import { requirePatientAccess } from '../middleware/authorizationMiddleware.js';
import { validatePatientIdParam } from '../validators/resourceValidator.js';
const router = Router({ mergeParams: true });
router.use(requireAuth, validatePatientIdParam, requirePatientAccess);
router.get('/', getPatientAnalytics);
router.get('/feature-vectors', getPatientFeatureVectors);
export default router;
